"""
Blog blueprint - serves static blog content at /blog
Generated by Next.js static export, copied to app/static/blog/
"""

from flask import Blueprint, send_from_directory, abort, current_app
import os

blog_bp = Blueprint('blog', __name__)


def get_blog_static_dir():
    """Get the blog static directory path, works in both local and Vercel"""
    # Try multiple paths for Vercel compatibility
    possible_paths = [
        os.path.join(current_app.root_path, 'static', 'blog'),
        os.path.join(os.path.dirname(os.path.dirname(__file__)), 'static', 'blog'),
        '/var/task/app/static/blog',  # Vercel's typical path
    ]
    for path in possible_paths:
        if os.path.exists(path):
            return path
    return possible_paths[0]  # Default to first option


@blog_bp.route('/')
def blog_index():
    """Serve blog homepage"""
    blog_dir = get_blog_static_dir()
    return send_from_directory(blog_dir, 'index.html')


@blog_bp.route('/<slug>')
def blog_post(slug):
    """Serve individual blog post"""
    blog_dir = get_blog_static_dir()
    # Next.js exports to blog/<slug>.html
    post_dir = os.path.join(blog_dir, 'blog')
    post_path = os.path.join(post_dir, f'{slug}.html')
    if os.path.exists(post_path):
        return send_from_directory(post_dir, f'{slug}.html')
    abort(404)


@blog_bp.route('/_next/<path:filename>')
def blog_assets(filename):
    """Serve Next.js static assets"""
    blog_dir = get_blog_static_dir()
    return send_from_directory(os.path.join(blog_dir, '_next'), filename)
