"""
Blog blueprint - serves static blog content at /blog
Generated by Next.js static export, copied to app/static/blog/
"""

from flask import Blueprint, send_from_directory, abort
import os

blog_bp = Blueprint('blog', __name__)

# Path to the static blog files
BLOG_STATIC_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'static', 'blog')


@blog_bp.route('/')
def blog_index():
    """Serve blog homepage"""
    return send_from_directory(BLOG_STATIC_DIR, 'index.html')


@blog_bp.route('/<slug>')
def blog_post(slug):
    """Serve individual blog post"""
    # Next.js exports to blog/<slug>.html
    post_path = os.path.join(BLOG_STATIC_DIR, 'blog', f'{slug}.html')
    if os.path.exists(post_path):
        return send_from_directory(os.path.join(BLOG_STATIC_DIR, 'blog'), f'{slug}.html')
    abort(404)


@blog_bp.route('/_next/<path:filename>')
def blog_assets(filename):
    """Serve Next.js static assets"""
    return send_from_directory(os.path.join(BLOG_STATIC_DIR, '_next'), filename)
